name: Deploy Niyo Group App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host ec2-host\n\tHostName 3.69.233.223\n\tUser ubuntu\n\tIdentityFile ~/.ssh/id_rsa\n\tStrictHostKeyChecking no" > ~/.ssh/config

      - name: SSH and Echo Greeting
        run:
          ssh ec2-host "echo 'Hello from EC2!'; hostname; uptime"
          # This command SSHs into the EC2 host, prints a greeting, the hostname, and uptime.

      - name: SSH and Change Directory
        run:
          ssh ec2-host "cd /home/ubuntu/niyo-group; echo 'Now in the desired directory'; hostname; uptime"
          # This command SSHs into the EC2 host, changes directory, and prints the status.

      - name: Install dependencies, build and restart PM2 on server
        env:
          PROJECT_PATH: /home/ubuntu/niyo-group
        run: |
          ssh ec2-host << 'EOF'
            cd $PROJECT_PATH
            git pull origin main
            npm install
            npm run build
            pm2 restart all || pm2 start dist/main.js --name 'niyogroup-app'
          EOF
